dataset = 'GCAAGCCGTTGGTCTTAACAATGGTTATCTAGAGGACATGCGTAAGTGGCGACCACTCACCCCCCGGTAGTTACACTACGAGCGTGTAAGTAAAAGCGGCGCCTAAATAGAGCATAGCAGCGTGGGCACACCGCAGTTAAAACTAGCCGTGCGAAGCGACGACCGGCTCGCGCGCAAAGTCACGAACGTGCCTACTAAATATTACTAGCCTGTGCTGGGGTTAGGGGCACTGTACGCACCGGTCTTCAGGGCGGGGTTTGCGTCGGCCAATAAAAGGTAACTTAGAGCCCTGTTGCTCCAGCGTTCAAGATGCTAGGCGTGAGCGTCTAACGTCCAGCGCATTCTACAAGTGCTCAGGTTTGGAGTCAGTGGTGAATGACACGTACAGTAGACAGCCGCTCCTGCCACCGCTTATGATAAATATTATAACAGTCTTAACTGTACACTCCTTCCGATTCTCTGCTAGCCTCAAACGACAGATACTGAGAGAGGTACTGAGGCGGCGAAGTCATTCAGGTAGGAGACTTTAACAGTCGTACGAACGAAACTGCAAATGAAAACCGAAGAGGTGGCCAGAGCTCTTAACCTTATCGAAAGGCCGAGGTACTTTGCGCCCGTGACCGCTAAGAGGCATCAATGAGTCCAGATGTCAGAAAGTATGCCTCGGTGAGCCCCTGTCAACCTGGGGAGATGTTATATATAACGACAATGAGCCACCAACGCTTACATCTTATTACCGAGAGATACACCCGTTTAAAGATAATTAGTCGGGGTGGACAATCGCAGGTTGCTTATCGGCATCTTGGGTTCTAGTACG'

output = [0,0,0,0]

for i in dataset:
    if i == 'A':
        output[0] += 1
    elif i == 'C':
        output[1] += 1
    elif i == 'G':
        output[2] += 1
    elif i == 'T':
        output[3] += 1

for i in output:
    print i,